version: '3.9'

services:
  store_back: 
    container_name: store_back
    tty: true
    build: ..
    volumes:
      - ../../store-backend:/opt/services/store-backend/
      - ../back_static:/opt/services/store-backend/back_static/
      - ../back_media:/opt/services/store-backend/back_media/
    entrypoint: "sh /opt/services/store-backend/scripts/wsgi_server.sh"
    ports:
      - "8000:8000"
    networks:
      - main-network
      - nginx-network
      - db-network

  db:
    image: postgres:14-alpine
    container_name: store_db
    restart: unless-stopped
    volumes:
      - ../storage:/var/lib/postgresql/data
    networks:
      - db-network
    env_file:
      - ../src/.env

  #redis:
  #  restart: always
  #  image: redis:alpine
  #  container_name: store_redis
  #  logging:
  #    driver: json-file
  #    options:
  #      max-size: "10m"
  #      max-file: "5"
  #  ports:  
  #  - "6379:6379"
  #  networks:
  #    - main-network
  #    - nginx-network

  nginx:
    image: nginx:1.13
    container_name: store_nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ../config/nginx/conf.d.dev:/etc/nginx/conf.d
      - ../back_static:/opt/services/store-backend/back_static/
      - ../back_media:/opt/services/store-backend/back_media/
    networks:
      - nginx-network
      - main-network

networks:
  nginx-network:
    driver: bridge
  db-network:
    driver: bridge
  main-network:
    driver: bridge

